challenges/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", views.challenge_view, name="main"),
    path("reading/<int:id>", views.challenge_reading_view, name="reading"),
    path("study/", views.challenge_study_view, name="study"),
    path("write/", views.write_challenge_view, name="write"),
    path("write/<tag>", views.challenge_tag_view, name="tag"),
]
app_name = "challenges"

connects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.connect_view, name="main"),
    path("dream/", views.connect_dream_view, name="dream"),
    path("challenge/", views.connect_challenge_view, name="challenge"),
]

app_name = "connects"

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.intro_view, name="intro"),
    path("try/", views.try_view, name="try"),
]

app_name = "core"

hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("records/", include("records.urls", namespace="records")),
    path("portfolios/", include("portfolios.urls", namespace="portfolios")),
    path("challenges/", include("challenges.urls", namespace="challenges")),
    path("connects/", include("connects.urls", namespace="connects")),
    path("repositories/", include("repositories.urls", namespace="repositories")),
    path("", include("core.urls", namespace="core")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.records_view, name="main"),
    path("write/", views.records_write_view, name="write"),
    path("calender/", views.records_calender_view, name="calender"),
    path("scrap/", views.records_write_scrap_view, name="scrap"),
]
app_name = "records"

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("main/", views.MainView.as_view(), name="main"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.log_out, name="logout"),
]

app_name = "users"

connects/models.py
from django.db import models

# Create your models here.

connects/views.py
from django.shortcuts import render

# Create your views here.


def connect_view(request):
    cld = {}
    cloud = request.GET.get("cloud", "health")
    cld["cloud"] = cloud
    print(cloud)
    return render(request, "connect/connect.html", cld)


def connect_dream_view(request):
    return render(request, "connect/connect_dream.html")


def connect_challenge_view(request):
    return render(request, "connect/connect_challenge.html")

templates/connect/connect.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}커넥트{% endblock page_title %}
{% block islogin %}
{% if request.user.is_authenticated %}
<a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
<a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}

{% block content%}

<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/connect/connect.css' %}">
    {% endblock css %}
</head>
<div class="outer">
    <div class="search">
        <div class="title"><strong>CONNECT :</strong><br>같은 꿈을 가진 사람들을 연결하다</div>
        <div class="search_bar">
            <form id="write-challenge" action="" method="POST">
                {% csrf_token %}
                <input class="search_box" name="search_box" type="text" placeholder="| 관심 분야를 검색해보세요"/>
            </form>
        </div>
    </div>
    <div class="portfolio">
        <div class="portfolio_title">현직자와 연결하기<br><p>관심 분야의 직업을 가진 사람들의 포트폴리오를 참고해보세요</p></div>
        <div class="border_categories">
            <ul>영업/영업관리 +</ul>
            <ul>마케팅/MD +</ul>
            <ul>전략/기획 +</ul>
            <ul>서비스기획/UI,UX +</ul>
            <ul>유통,무역,구매 +</ul>
            <ul>IT개발 +</ul>
            <ul>연구/설계 +</ul>
            <ul>공사/공기업 +</ul>
            <ul>미디어 +</ul>
            <ul>홍보/CSR +</ul>
            <ul>인사/총무/노무 +</ul>
            <ul>회계/재무/금융 +</ul>
            <ul>생산/품질/제조 +</ul>
            <ul>공무원/비영리 +</ul>
            <ul>기타 사무 +</ul>
            <ul>디자인/예술 +</ul>
            <ul>...</ul>
        </div>
        <div class="profiles">
            <div class="detail_box">
                <img src="{% static 'image/connect_profile_doohee.jpeg' %}" class="detail_box_photo"></img>
                <div class="detail_box_texta"><strong>IT개발</strong><br>내 아이디어를 내 손으로 실현한다</div>
            </div>
            <div class="detail_box">
                <img src="{% static 'image/connect_portfolio1.png' %}" class="detail_box_photo"></img>
                <div class="detail_box_texta"><strong>IT개발</strong><br>꿈은 크게 꾸는 것</div>
            </div>
            <div class="detail_box">
                <img src="{% static 'image/connect_portfolio2.png' %}" class="detail_box_photo"></img>
                <div class="detail_box_texta"><strong>IT개발</strong><br>편견을 깨는 것이 중요</div>
            </div>
            <div class="detail_box">
                <img src="{% static 'image/connect_portfolio3.png' %}" class="detail_box_photo"></img>
                <div class="detail_box_texta"><strong>IT개발</strong><br>상상만 하는 것과 구현하는 것은 다릅니다</div>
            </div>
            <div class="detail_box">
                <img src="{% static 'image/connect_portfolio4.png' %}" class="detail_box_photo"></img>
                <div class="detail_box_texta"><strong>IT개발</strong><br>한계는 없다: limitless</div>
            </div>
            <div class="detail_box">
                <img src="{% static 'image/connect_portfolio5.png' %}" class="detail_box_photo"></img>
                <div class="detail_box_texta"><strong>IT개발</strong><br>사용자들의 삶을 편리하게!</div>
            </div>
        </div>
    </div>
    <div class="challenge">
        <div class="challenge_title">챌린지 함께하기<br><p>함께 하면 성공할 확률이 높아져요</p></div>
        <!-- <div class="challenge_smalltitle">함께 하면 성공할 확률이 높아져요</div> -->
        <div class="challenge_categories">
            <a href="?cloud=health" class="challenge_category_boxes"># 건강</a>
            <a href="?cloud=study" class="challenge_category_boxes"># 공부</a>
            <a href="?cloud=work" class="challenge_category_boxes"># 업무</a>
            <a href="?cloud=reading" class="challenge_category_boxes"># 독서</a>
            <a href="?cloud=habbit" class="challenge_category_boxes"># 습관</a>
            <a href="?cloud=hobby" class="challenge_category_boxes"># 취미</a>
        </div>
        <div class="cloud"><img src="/static/image/cloud_{{cloud}}.png"></img></div>
    </div>
    <div class="contest_exhibit">
        <div class="contest_exhibit_title">활동 함께하기<br><p>관심 분야의 공모전/스터디를 함께할 사람을 찾아보세요</p></div>
        <div class="profiles">
            <div class="contest_exhibit_subtitle"><i class="fas fa-bullhorn"></i><p>공모전 함께하기</p></div>
            <div class="contest_exhibit_categories">
                <ul>전체</ul>
                <ul>아이디어/기획</ul>
                <ul>광고/마케팅</ul>
                <ul>미디어</ul>
                <ul>디자인</ul>
                <ul>글쓰기</ul>
                <ul>소프트웨어</ul>
                <ul>공학/과학</ul>
                <ul>기타 +</ul>
            </div>
            <div class="contest_exhibit_boxes">
                <div class="detail_box">
                    <div class="expln">
                        클릭해보세요!!👇
                        </div>
                    <a href="{% url 'connects:dream' %}">
                    <img src="{% static 'image/poster_new.jpeg' %}" class="detail_box_photo">
                    </img>
                    <div class="detail_box_text"><strong>데이터 분석 공모전</strong><br>코딩 잘 몰라도 아이디어 넘치시는 분!성실하신 분!함께해요~:)</div>
                    </a>
                </div>
                <div class="detail_box">
                    <img src="{% static 'image/poster2.jpeg' %}" class="detail_box_photo"></img>
                    <div class="detail_box_text"><strong>IT 관련 아이디어 공모전</strong><br>경험 유무 상관x, 초보자도 환영!_! 열정만 있으면 OK</div>
                </div>
                <div class="detail_box">
                    <img src="{% static 'image/poster3.jpeg' %}" class="detail_box_photo"></img>
                    <div class="detail_box_text"><strong>보안 관련 해커톤</strong><br>흔치 않은 "보안" 관련 해커톤 기회를 잡으세요~~!!(with us)</div>
                </div>
                <div class="detail_box">
                    <img src="{% static 'image/poster4.jpeg' %}" class="detail_box_photo"></img>
                    <div class="detail_box_text"><strong>스마트시티 영상 공모전</strong><br>영상 툴 다룰 줄 아시는 분 환영** 개발은 저희가 합니다</div>
                </div>
            </div>
            <div class="study_title"><i class="fas fa-chalkboard-teacher"></i><p>스터디 함께하기</p></div>
            <div class="contest_exhibit_categories">
                <ul>전체</ul>
                <ul>자격증</ul>
                <ul>어학</ul>
                <ul>면접</ul>
                <ul>고시/공부</ul>
                <ul>교양</ul>
                <ul>프로그래밍</ul>
                <ul>기타 +</ul>    
            </div>
            <div class="study_boxes">
                <div class="detail_box_study">
                    <div class="detail_box_text"><p1># 파이썬 스터디<br></p1><div class="gap"></div><p2>
                        파이썬 처음 배우시는 분들~~ 모두 함께 공부해요 !_! </p2></div>
                </div>
                <div class="detail_box_study">
                    <div class="detail_box_text"><p1># 리액트 스터디<br></p1><div class="gap"></div>
                    <p2>리액트 스터디원 모집해요~!!</p2></div>
                </div>
                <div class="detail_box_study">
                    <div class="detail_box_text"><p1># 코테 스터디<br></p1><div class="gap"></div>
                    <p2>코테 스터디원 모집합니다</p2></div>
                </div>
                <div class="detail_box_study">
                    <div class="detail_box_text"><p1># 기상 스터디<br></p1><div class="gap"></div>
                    <p2>오전 9시에 도서관에서 출첵하실분~!!</p2></div>
                </div>
                <div class="detail_box_study">
                    <div class="detail_box_text"><p1># 알고리즘 스터디<br></p1><div class="gap"></div>
                    <p2>상 난이도 코테 문제 함께 푸실 분들 모집합니다</p2></div>
                </div>
                <div class="detail_box_study">
                    <div class="detail_box_text"><p1># 웹 프로그래밍<br></p1><div class="gap"></div>
                    <p2>다음 달 열리는 중앙해커톤 준비 같이하실 분~~ 모집해영</p2></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
<!-- <script src="{% static 'js/portfolio.js' %}" ></script> -->
<script src="{% static 'js/emoji.js' %}" ></script>
{% endblock content%}

templates/connect/connect_challenge.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}Connect ppl{% endblock page_title %}
{% block islogin %}
{% if request.user.is_authenticated %}
<a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
<a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}
{% block content%}

<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/challenge/challenge.css' %}">
    {% endblock css %}
        <div class="head_title">나의 챌린지</div>
        <div class="logo">
            <img src="{% static 'image/facebook.svg' %}" alt="facebook">
            <img src="{% static 'image/instagram.svg' %}" alt="instagram">
            <img src="{% static 'image/share.svg' %}" alt="shareIcon">
        </div>
        <div class="line_parent"><div class="line"></div></div>
</head>
<div class="round-all">
    <div class="round"><a href="{% url 'challenges:reading' %}"><img src="{% static 'image/challenge_reading.jpeg' %}" alt="img"/><p>매일 20페이지 읽기</p></a></div>
    <div class="round"><a href="{% url 'challenges:study' %}"><img src="{% static 'image/challenge_study.png' %}" alt="img"/><p>매일 1시간 공부</p></a></div>
    <div class="round"><a href="#"><img src="{% static 'image/challenge_alarmclock.jpeg' %}" alt="img"/><p>평일 오전 6시 기상</p></a></div>
    <div class="round"><a href="{% url 'challenges:write' %}"><div class = "nothing"><div class="plus">+</div></div>
        <p>새로운 챌린지</p>
    </a></div>   
</div>
{% endblock content%}

templates/connect/connect_dream.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}활동을 커넥트하다;{% endblock page_title %}
{% block islogin %}
{% if request.user.is_authenticated %}
<a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
<a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}
{% block content%}

<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/connect/connect_dream.css' %}">
    {% endblock css %}
</head>

<div class="space_all">
    <div class="contents_all">
        <div class="box">
            <div class="poster"><img src="{% static 'image/poster_new.jpeg' %}"></img>
            </div>
            <div class="others">
                <div class="contents_detail">
                    <br>해양학과/물류학과/컴퓨터공학과 환영!_! 
                    <br>평소 실생활에서 아이디어 많이 생각해 보신분도 환영 !_!
                    팀장이 공모전 경험 많아서 성실하게만 참여하면 수상도 가능 !!
                    부담갖지 말고 <div class="p22">" 상단 바의 NADA 메세지 "</div>를 보내주세요~~~
                </div>
                <button class="other_team" type="button">이 공모전의 다른 팀 확인하기</button>
                <button class="others_portfolio" type="button">팀장의 포트폴리오 참고하기</button>
            </div>
        </div>
        <div class="emoji">
                <f class="emoji_box">
                    <i class="fas fa-heart fa-lg heartclick"></i>
                </f>
                <f class="emoji_box"><a href="http://www.facebook.com/"><img src="{% static 'image/facebook.svg' %}" alt="facebook"></a></f>
                <f class="emoji_box"><a href="http://www.instagram.com/"><img src="{% static 'image/instagram.svg' %}" alt="instagram"></a></f>
                <f class="emoji_box"><img src="{% static 'image/share.svg' %}" alt="share"></f>
        </div>
    </div>
    <button class="buttonyy" type="submit">내 포트폴리오 공유하기</button>
    </div>
</div>



<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
<script src="{% static 'js/portfolio.js' %}" ></script>
{% endblock content%}