core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.intro_view, name="intro"),
    path("try/", views.try_view, name="try"),
]

app_name = "core"

hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("records/", include("records.urls", namespace="records")),
    path("portfolios/", include("portfolios.urls", namespace="portfolios")),
    path("challenges/", include("challenges.urls", namespace="challenges")),
    path("connects/", include("connects.urls", namespace="connects")),
    path("repositories/", include("repositories.urls", namespace="repositories")),
    path("", include("core.urls", namespace="core")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.portfolio_view, name="main"),
    path("dehee/", views.portfolio_dohee_view, name="dohee"),
    path("compare/", views.portfolio_compare_view, name="compare"),
]

app_name = "portfolios"

records/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.records_view, name="main"),
    path("write/", views.records_write_view, name="write"),
    path("calender/", views.records_calender_view, name="calender"),
    path("scrap/", views.records_write_scrap_view, name="scrap"),
]
app_name = "records"

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("main/", views.MainView.as_view(), name="main"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.log_out, name="logout"),
]

app_name = "users"

portfolios/models.py
from django.db import models

# Create your models here.

portfolios/views.py
from django.shortcuts import render
from records import models as record_models
from challenges import models as challenge_models
import json

# Create your views here.


def portfolio_view(request):
    age = 22
    ages = [
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
    ]
    data = [
        "3",
        "-1",
        "5",
        "7",
        "-4",
        "-1",
    ]
    text = [
        "인생 친구를 만남",
        "지리 올림피아드 은상",
        "인하대 합격",
        "고교 멘토링 활동",
        "군 입대",
        "군 전역",
    ]
    if request.POST:
        age += 1
        ages.append(str(age))
        text.append(str(request.POST.get("text1", "")))
        data.append(str(request.POST.get("number1", "0")))
    print(ages, data, text)
    data = json.dumps({"data": data})
    text = json.dumps({"text": text})
    ages = json.dumps({"ages": ages})

    records = record_models.Record.objects.all().order_by("start_date")
    # records = (
    #     record_models.Record.objects.all()
    #     .values_list("title", "start_date", "end_date")
    #     .union(
    #         challenge_models.Challenge.objects.all().values_list(
    #             "title", "start_date", "end_date"
    #         )
    #     )
    # )

    return render(
        request,
        "portfolio/portfolio.html",
        {"data": data, "text": text, "records": records, "ages": ages, "age": age},
    )


def portfolio_dohee_view(request):
    return render(request, "portfolio/portfolio_dohee.html")


def portfolio_compare_view(request):
    records = record_models.Record.objects.all()
    year = []
    for record in records:
        year.append(record.start_date.year)

    years = sorted(list(set(year)))
    return render(
        request,
        "portfolio/portfolio_compare.html",
        {"years": years, "records": records},
    )

templates/portfolio/portfolio.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/portfolio/portfolio.css' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}

<!--User Profile-->
{% block islogin %}
{% if request.user.is_authenticated %}
    <a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
    <a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}


    

{% block content %}
<div class="left_right_all_page">
    <div></div>
    <div class="portfolio_main">
        <div class="index_two">
            <div class="index_two_box">
                <span class="index_two_box_title">PORTFOLIO</span>
                <span class="index_two_box_title_sub">인생 곡선을 담은 나만의 포트폴리오</span>
            </div>
        </div>
        <div class="index_three">
            <div class="index_three_one_window">
                <div class="index_three_one_window_flex">
                    <div class="name_doohee"></div>
                    <div class="index_three_real_one_window">
                        <img class="image" src="{% get_media_prefix %}/{{user.avatar}}">
                    </div>
                </div>
            </div>
            <div class="index_three_window">
                <div class="index_three_real_window">
                    <img class="images" src="{% static 'image/it.png'%}"></img>
                    <div class="index_three_text">
                        <span class="index_three_text_one">{{user.username}}</span>
                        <span class="index_three_text_two">seungchanlee@likelion.org</span>
                        <span class="index_three_text_three">인하대학교 공간정보공학과/소프트웨어융합공학,<br>인하대 멋쟁이사자처럼 9기,<br>[나다] 웹서비스 창립멤버</span>
                    </div>
                </div>
                <div class="profile_first_page_right_nav">
                    <div class="profile_first_page_right_nav_one">
                        <i class="fas fa-heart fa-2x heartclick"></i>
                    </div>
                    <div class="empty"></div>
                    <a href="{% url 'portfolios:dohee' %}">
                        <div class="profile_first_page_right_nav_two">
                            <i class="fas fa-sign-in-alt fa-2x"></i>
                        </div>
                    </a>
                    <div class="empty"></div>
                    <div class="profile_first_page_right_nav_three">
                        <i class="far fa-folder fa-2x">
                        </i>
                    </div>
                </div>
            </div>
        </div>
        <div class="index_four">
            <div class="index_four_one_window">
                <div class="index_four_real_one_window">
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ff">학점 :</div>
                        <span class="big">3.72</span>
                    </div>
                    <div class="index_four_real_one_window_flex">    
                        <div class="index_four_real_one_window_ffa">어학 : </div>
                        <span class="biga">Toeic(820), OPIC(AL)</span>
                    </div>
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ffb">자격증 : </div>
                        <span class="bigb">한국사능력검정 자격증<br>컴퓨터활용능력 1급</span>
                    </div>
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ffc">수상 : </div>
                        <span class="bigc">멋사 중앙해커톤 TOP 10</span>
                    </div>
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ffd">경력 : </div>
                        <span class="bigd">광교 스시집 알바 3개월</span>
                    </div>
                </div>
            </div>
            <div class="index_four_window">

                <a href="{% url 'portfolios:compare' %}" class="compare_box">
                    <div class="compare">compare</div>
                </a>

                <div class="index_four_real_window">
                    <canvas id="line-chart" ></canvas>
                </div>
                <form action="{% url 'portfolios:main' %}" method="POST">
                    {% csrf_token %}
                    <label for="username">사용자 이름</label>
                    <input id="username"  name="username" value="{{user.username}}" placeholder="이름을 입력하세요"><br>
                    <label for="num1">{{age|add:"1"}}살</label>
                    <input id="num1" type="number" name="number1">
                    <label for="text1">설명</label>
                    <input id="text1" type="text" name="text1" placeholder="설명을 입력하세요">
                    
                    <button type="submit" >확인하기</button>
                </form>
            </div>
        </div>
        <div class="index_five">
            <div class="index_five_title">
                <div class="index_five_title_left">
                    <div class="index_five_title_one">02. ACTIVITY&ensp;&ensp;</div>
                    <div class="index_five_title_two"></div>
                </div>
            <div class="head_title">
                <p class="bling">새로운 기록을 작성해 보세요    >>>>>></p>
            </div>
            <a href="{% url 'records:write' %}">
                <div class="activity_add">추가하기</div>
            </a>
            </div>
            <div class="index_five_window">
                <div class="activity_box">
                    
                    {% for record in records %}
                        <div href="" class="activity_graph">
                            <div class="activity_graph__point"></div>
                            <div class="activity_graph__year">{{record.start_date|date:"Y"}}</div>
                            <div class="activity_graph__line"></div>
                            <p class="activity_date">{{record.start_date|date:"M d일"}} ~ {{record.end_date|date:"M d일"}}</p>
                            <p class="activity_name">{{record.title}}</p>
                        </div>
                        
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="index_six">
            <div class="index_six_title">
                <div class="index_six_title_text">03. REFERENCE</div>
            </div>
            <div class="index_six_window">
                <div class="index_six_real_window">
                    <div class="index_six_real_window_grid_one">
                        <div class="index_six_real_window_grid_one_up">
                            <div class="index_six_real_window_grid_one_up_image">
                                <img class="image" src="{% static 'image/info.gif'%}"></img>
                            </div>
                        </div>
                        <div class="index_six_real_window_grid_one_down">
                            <div class="index_six_real_window_grid_one_down_text">정보처리기사 자격증</div>
                        </div>
                    </div>
                    <div class="index_six_real_window_grid_two">
                        <div class="index_six_real_window_grid_two_up">
                            <div class="index_six_real_window_grid_two_up_image">
                                <img class="image" src="{% static 'image/computer.jpeg'%}"></img>
                            </div>
                        </div>
                        <div class="index_six_real_window_grid_two_down">
                            <div class="index_six_real_window_grid_two_down_text">컴퓨터활용능력 1급 자격증</div>
                        </div>
                    </div>
                    <div class="index_six_real_window_grid_three">
                        <div class="index_six_real_window_grid_three_up">
                            <div class="index_six_real_window_grid_three_up_image">+</div>
                        </div>
                        <div class="index_six_real_window_grid_three_down">
                            <div class="index_six_real_window_grid_two_down_text">추가하기</div>
                        </div>
                    </div>
                    <div class="index_six_real_window_grid_four"></div>
                    <div class="index_six_real_window_grid_five"></div>
                    <div class="index_six_real_window_grid_six"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script>
        var text = {{text|safe}}.text
        var ages = {{ages|safe}}.ages
        var data = {{data|safe}}.data
        var labels =   []
        var score =   []
        for (var i = 0; i < text.length; i++) { 
            age = Number(ages[i])
            labels.push([age,text[i]])
            score.push(Number(data[i]))
    }
        var chart = new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
            labels:labels,
            datasets: [
                /*{ 
                data: [5,1,6,6,7,1,3,9,8,8],
                label: "이두희",
                borderColor: "#3e95cd",
                fill: false
            }, */
            { 
                data: score,
                label: "{{request.user}}",
                borderColor: "#8e5ea2",
                fill: false
            }
        ]
        },
        options: {
            title: {
            display: true,
            text: "{{request.user}}'s Lifecycle",
            fontSize: 50,
            
            
            }
        }
    
        })
        canvas = document.querySelector("canvas")
        canvas.style.cssText="display:block; width:100%; height:100%;"
        ;
    </script>
<script src="{% static 'js/portfolio.js' %}" ></script>
{% endblock content %}

templates/portfolio/portfolio_compare.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/portfolio/portfolio_compare.css' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}

<!--User Profile-->
{% block islogin %}
{% if request.user.is_authenticated %}
    <a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
    <a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}
{% block content %}
<div class="cbody">
    <div class="graphbox">
        <div class="graph_title">일론 머스크님과 비교 그래프 <span class="mannai">(만 나이)</span></div>
        <div class="gradation_box">
            <div class="gradation_box__top">
                {% for year in years %}
                <div class="gradations">
                    <div class="gradations_detail">
                        {% for record in records %}
                        {% if record.start_date.year == year %}
                        <p class="gradations_top_detail">• {{record.title}}</p>
                        {% endif %}
                        {% endfor %}
                        <div class="emp"></div>
                        </div>
                    </div>
            
                
                {% endfor %}
             
            </div>
            <div class="gradation_box__bottom">
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">19</p><p class="gradations_bottom_detail">• 퀸즈 대학교 물리학 전공</p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">20</p><p class="gradations_bottom_detail"></p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">21</p><p class="gradations_bottom_detail">• 펜실베니아 대학교 편입</p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">22</p><p class="gradations_bottom_detail">• 로켓 사이언스 게임스 인턴</p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age now">23<span>now</span></p><p class="gradations_bottom_detail">• 펜실베니아 대학교 물리학, 경제학 학사</p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">24</p><p class="gradations_bottom_detail">• 스텐포드대 자퇴, ZIP2설립</p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">25</p><p class="gradations_bottom_detail"></p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">26</p><p class="gradations_bottom_detail"></p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">27</p><p class="gradations_bottom_detail"></p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">28</p><p class="gradations_bottom_detail">• X.com(Paypal 전신) 설립</p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">29</p><p class="gradations_bottom_detail"></p>
                    </div>
                </div>
                <div class="gradations">
                    <div class="agebox">
                        <p class="age">30</p><p class="gradations_bottom_detail">• Space X설립 </p>
                    </div>
                </div>
                
               
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/portfolio/portfolio_dohee.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/portfolio/portfolio.css' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}

<!--User Profile-->
{% block islogin %}
{% if request.user.is_authenticated %}
    <a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
    <a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}


    

{% block content %}
<div class="left_right_all_page">
    <div></div>
    <div class="portfolio_main">
        <div class="index_two">
            <div class="index_two_box">
                <span class="index_two_box_title">PORTFOLIO</span>
                <span class="index_two_box_title_sub">Elon Musk의 포트폴리오</span>
            </div>
        </div>
        <div class="index_three">
            <div class="index_three_one_window">
                <div class="index_three_one_window_flex">
                    <div class="name_dooheeqq"></div>
                    <div class="index_three_real_one_window">
                        <img class="image" src="{%static 'image/elonmusk.png'%}">
                    </div>
                </div>
            </div>
            <div class="index_three_window">
                <div class="index_three_real_window">
                    <img class="images" src="{% static 'image/spaceman.webp'%}"></img>
                    <div class="index_three_text">
                        <span class="index_three_text_one">Elon musk</span>
                        <span class="index_three_text_two">gotomars@likelion.org</span>
                        <span class="index_three_text_three">펜실베니아 대학교 물리학 , 경제학 학사<br>테슬라, 스페이스X, 솔라시티, 뉴럴링크, 보링컴퍼니 CEO<br>ZIP2, X.com, PayPal 전 창립 멤버<br>51세, 만50세, 남아프리카공화국 태생</span>
                    </div>
                </div>
                <div class="profile_first_page_right_nav">
                    <div class="profile_first_page_right_nav_one">
                        <i class="fas fa-heart fa-2x heartclick"></i>
                    </div>
                    <div class="empty"></div>
                    <div class="profile_first_page_right_nav_three">
                        <i class="far fa-folder fa-2x">
                        </i>
                    </div>
                </div>
            </div>
        </div>
        <div class="index_four">
            <div class="index_four_one_window">
                <div class="index_four_real_one_window">
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ff">학점 :</div>
                        <span class="big">4.12</span>
                    </div>
                    <div class="index_four_real_one_window_flex">    
                        <div class="index_four_real_one_window_ffa">어학 : </div>
                        <span class="biga">영어(모국어)</span>
                    </div>
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ffb">자격증 : </div>
                        <span class="bigb">한국사능력검정시험</span>
                    </div>
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ffc">수상 : </div>
                        <span class="bigc">국제 CEO 아이디어 경진대회<br>친환경 자동차 대회</span>
                    </div>
                    <div class="index_four_real_one_window_flex">
                        <div class="index_four_real_one_window_ffd">경력 : </div>
                        <span class="bigd">페이팔 공도 창업자, OPEN AI 고문, 테슬라<br>스페이스X, 솔라시티, 뉴럴링크</span>
                    </div>
                </div>
            </div>
            <div class="index_four_window">
                <div class="index_four_real_windowqq">
                    <canvas id="line-chart" ></canvas>
                </div>
            </div>
        </div>
        
    </div>
</div>
<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script>
        var text = {{text|safe}}.text
        var labels =   [[20],[21],[22],[23],[24],[25],[26],[27],[28],[29]]
        for (var i = 0; i < text.length; i++) { 
            labels[i].push(text[i])
    }
        var chart = new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
            labels:labels,
            datasets: [
                /*{ 
                data: [5,1,6,6,7,1,3,9,8,8],
                label: "이두희",
                borderColor: "#3e95cd",
                fill: false
            }, */
            { 
                data: [{{data|safe}}.data[0].num1,{{data|safe}}.data[0].num2,{{data|safe}}.data[0].num3,{{data|safe}}.data[0].num4,{{data|safe}}.data[0].num5,{{data|safe}}.data[0].num6,{{data|safe}}.data[0].num7,{{data|safe}}.data[0].num8,{{data|safe}}.data[0].num9,{{data|safe}}.data[0].num10],
                label: {{data|safe}}.data[0].username,
                borderColor: "#8e5ea2",
                fill: false
            }
        ]
        },
        options: {
            title: {
            display: true,
            text: 'Check your lifecycle graph with DooHee',
            fontSize: 50,
            
            
            }
        }
    
        })
        canvas = document.querySelector("canvas")
        canvas.style.cssText="display:block; width:100%; height:100%;"
        console.log(chart)
        ;
    </script>
<script src="{% static 'js/portfolio.js' %}" ></script>
{% endblock content %}