core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.intro_view, name="intro"),
    path("try/", views.try_view, name="try"),
]

app_name = "core"

hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("records/", include("records.urls", namespace="records")),
    path("portfolios/", include("portfolios.urls", namespace="portfolios")),
    path("challenges/", include("challenges.urls", namespace="challenges")),
    path("connects/", include("connects.urls", namespace="connects")),
    path("repositories/", include("repositories.urls", namespace="repositories")),
    path("", include("core.urls", namespace="core")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.records_view, name="main"),
    path("write/", views.records_write_view, name="write"),
    path("calender/", views.records_calender_view, name="calender"),
    path("scrap/", views.records_write_scrap_view, name="scrap"),
]
app_name = "records"

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("main/", views.MainView.as_view(), name="main"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.log_out, name="logout"),
]

app_name = "users"

records/models.py
from django.db import models
from core import models as core_models
from users import models as user_models

# Create your models here.


class Record(core_models.TimeStampedModel):
    title = models.CharField(max_length=50)
    category = models.CharField(max_length=50, null=True, blank=True)
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    detail = models.TextField()
    thumbnail = models.ImageField(default=True, blank=True)

records/views.py
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from . import models as record_models
from challenges import models as challenge_models
import random
import datetime

# Create your views here.


def records_view(request):
    page = int(request.GET.get("page", 1) or 1)
    queryset = (
        record_models.Record.objects.filter(category="licence")
        | record_models.Record.objects.filter(category="language")
        | record_models.Record.objects.filter(category="grade")
        | record_models.Record.objects.filter(category="internship")
        | record_models.Record.objects.filter(category="volunteer")
        | record_models.Record.objects.filter(category="work")
    )
    records = record_models.Record.objects.all().order_by("-updated")
    reco = record_models.Record.objects.all().filter(
        end_date__lte=datetime.datetime.now()
    )
    all = (
        challenge_models.Challenge.objects.all()
        .values_list("title", "thumbnail", "start_date", "updated")
        .union(reco.values_list("title", "thumbnail", "start_date", "updated"))
    )
    all = (
        all.values_list("title", "thumbnail", "start_date", "updated")
        .union(queryset.values_list("title", "thumbnail", "start_date", "updated"))
        .order_by("-updated")
    )
    p = Paginator(all, 6)
    all = p.get_page(page)
    return render(
        request,
        "records/records.html",
        {"queryset": queryset, "records": records, "all": all},
    )


def records_write_view(request):
    if request.POST:
        title = request.POST.get("title")
        start_date = request.POST.get("start_date")
        end_date = request.POST.get("end_date")
        category = request.POST.get("category")
        startyear, startmonth, startday = (
            int(start_date[:4]),
            int(start_date[5:7]),
            int(start_date[8:10]),
        )
        start_date = datetime.date(startyear, startmonth, startday)
        endyear, endmonth, endday = (
            int(end_date[:4]),
            int(end_date[5:7]),
            int(end_date[8:10]),
        )
        end_date = datetime.date(endyear, endmonth, endday)
        period = end_date - start_date
        print(period)
        detail = request.POST.get("detail")
        random_number = random.randint(1, 6)
        thumbnail = f"records/record_{random_number}.png"
        record_models.Record.objects.create(
            title=title,
            start_date=start_date,
            end_date=end_date,
            category=category,
            detail=detail,
            thumbnail=thumbnail,
        )
        return redirect("portfolios:main")

    return render(request, "records/records_write.html")


def records_calender_view(request):
    return render(request, "records/records_calender.html")


def records_write_scrap_view(request):
    return render(request, "records/records_write_scrap.html")

templates/records/records.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/records/records.css' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}
{% block islogin %}
{% if request.user.is_authenticated %}
<a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
<a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}
{% block content %}
<div class="left_right_all_page">
    <div></div>
    <div class="portfolio_main">
        <div class="index_two">
            <div class="index_two_box">
                <span class="index_two_box_title">RECORD</span>
                <div class="index_two_box_title_sub">Record에 당신의 모든 기록을 저장해 보세요</div>
            </div>
        </div>
        <div class="index_three">
            <div class="index_three_title">
                <div class="index_three_title_one">전체보기</div>
            </div>
            <div class="index_three_window">
                <div class="topbar">
                    <p></p>
                    <p class="index_three_window_sixmother_title">2021년 8월</p>
                    <div class="listbox" ><i class="fas fa-th-list "></i><i class="fas fa-list "></i><i class="fas fa-th "></i></div>
                    
                </div>
                <div class="index_three_window_sixmother">
                    <!--
                            <div class="index_three_window_box">

                            <div class="index_three_window_one">
                                <img class="images" src="{% static 'image/like_lion.png'%}"></img>
                            </div>
                        </div>
                        -->
                    {% for title,thumbnail,start,updated in all %}
                    <div class="index_three_window_box">
                        <div class="index_three_window_one">
                            <img class="index_three_window_one" src="{% get_media_prefix %}/{{thumbnail}}"></img>

                        </div>
                        <p class="picture_title">{{title}}</p>
                    </div>
                    {% endfor %}
                    
                    
                </div>
                <div class="index_three_window_under">
                    {% if all.has_previous %}
                        <a href="?page={{all.previous_page_number}}"> <i class="fas fa-arrow-circle-left fa-2x"></i> </a>
                    {% endif %}
                    
                    <span>&ensp;&ensp;{{all.number}}/{{all.paginator.num_pages}}&ensp;&ensp;</span>
                    {% if all.has_next %}
                        <a href="?page={{all.next_page_number}}"> <i class="fas fa-arrow-circle-right fa-2x"></i> </a>
                    {% endif %}
                    
                </div>
            </div>
        </div>
        <div class="index_four">
            <div class="index_four_title">
                <div class="index_four_title_text">당신이 작성한 포트폴리오</div>
                <div class="index_four_title_date">2021년 8월</div>
            </div>
            <div class="index_four_window">
                <div class="portbox">
                    {% for record in records %}
                    <div class="port">
                        <img class="port_img" src="{% get_media_prefix %}/{{record.thumbnail}}"/>
                        <div class="port_title">{{record.title}}</div>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
            <div class="recbtn">
                <a href="{% url 'records:write' %}" class="index_four_real_window_grid_six_plus_box_plus">
                    <span class="rec_btn">기록하기</span>
                </a href="{% url 'records:write' %}">

            </div>
        <div class="index_five">
            <div class="index_five_title">
                <div class="index_five_title_text">완료한 챌린지</div>
                <div class="index_five_title_date">2021년 8월</div>
            </div>
            <div class="index_five_window">
                <div class="index_five_window_flex">
                <div class="index_five_window_box"># 전체</div>
                <div class="emptyq"></div>
                <div class="index_five_window_box"># 공부</div>
                <div class="emptyq"></div>
                <div class="index_five_window_box"># 건강</div>
                <div class="emptyq"></div>
                <div class="index_five_window_box"># 습관</div>
                <div class="emptyq"></div>
                <div class="index_five_window_box"># 독서</div>
                <div class="emptyq"></div>
                <div class="index_five_window_box"># 취미</div>
                <div class="emptyq"></div>
                <div class="index_five_window_box"># 업무</div>
                <div class="emptyq"></div>
                </div>
            </div>
            <div class="under_bar"></div>
            <div class="under_box">
                <div class="under_box_boxa">
                    <div class="under_box_one">
                        <div class="under_box_one_pic"></div>
                        <span class="complete">
                            <span>Completed</span>
                        </span>
                    </div>
                </div>
                <div class="under_box_boxa">
                    <div class="under_box_two">
                        <div class="under_box_one_pic">
                        </div>
                        <span class="complete">
                            <span>Completed</span>
                        </span>
                    </div>
                </div>
                <div class="under_box_boxa">
                    <div class="under_box_three">
                        <div class="under_box_one_pic">
                        </div>
                        <span class="complete">
                            <span>Completed</span>
                        </span>
                    </div>
                </div>
                <div class="under_box_four"></div>
                <div class="under_box_five">
                    <span>30일 코딩</span>
                    <div class="level_box">
                        <div class="levela"></div>
                    </div>
                    <span>달성률: 60%</span>
                </div>
                <div class="under_box_six">
                    <span>30일 독서</span>
                    <div class="level_box">
                        <div class="levelb"></div>
                    </div>
                    <span>달성률: 52%</span>
                </div>
                <div class="under_box_seven">
                    <span>30일 운동</span>
                    <div class="level_box">
                        <div class="levelc"></div>
                    </div>
                    <span>달성률: 31%</span>
                </div>
                <div class="under_box_eight"></div>
            </div>
        </div>
        <div class="index_six">
            <div class="index_six_title">
                <div class="index_six_title_text">스크랩</div>
                <div class="index_six_title_date">2021년 8월</div>
            </div>
            <div class="index_six_window">
                <div class="index_six_real_window">
                    <div class="index_six_real_window_grid_one">
                        <div class="index_six_real_window_grid_one_up">
                            <div class="index_six_real_window_grid_one_up_image">
                                <img class="image" src="{% static 'image/news_one.png'%}"></img>
                            </div>
                        </div>
                        <div class="index_six_real_window_grid_one_down">
                            <div class="index_six_real_window_grid_one_down_text">7월 29일 매일경제 빅데이터</div>
                        </div>
                    </div>
                    <div class="index_six_real_window_grid_two">
                        <div class="index_six_real_window_grid_two_up">
                            <div class="index_six_real_window_grid_two_up_image">
                                <img class="image" src="{% static 'image/news_two.png'%}"></img>
                            </div>
                        </div>
                        <div class="index_six_real_window_grid_two_down">
                            <div class="index_six_real_window_grid_two_down_text">7월 29일 동아경제 살균</div>
                        </div>
                    </div>
                    <div class="index_six_real_window_grid_three">
                        <div class="index_six_real_window_grid_three_up">
                            <div class="index_six_real_window_grid_three_up_image"></div>
                        </div>
                        <div class="index_six_real_window_grid_three_down">
                            <div class="index_six_real_window_grid_two_down_text">n월 n일 OO일보 OO</div>
                        </div>
                    </div>
                    <div class="index_six_real_window_grid_four"></div>
                    <div class="index_six_real_window_grid_five"></div>
                    <a class="index_six_button" href="{% url 'records:scrap' %}">
                        <div class="index_six_real_window_grid_six_plus_box_plus">
                            <span>작성하기</span>
                        </div>
                    </a>  
                </div>
            </div>
        </div>
    </div>
</div>
<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>

{% endblock content%}

templates/records/records_write.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/records/records_write.css' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}
{% block islogin %}
{% if request.user.is_authenticated %}
<a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
<a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}
{% block content %}
<div class="left_right_all_page">
    <div></div>
    <div class="portfolio_main">
        <form class="index_three" method="POST" action="{% url 'records:write' %}">
            {% csrf_token %}
            <div class="index_three_window">
                <label class="grid_one">
                    <span>카테고리:&nbsp;</span>
                </label>
                <div class="grid_two">
                    <select name="category" id="category">
                        <optgroup label="포트폴리오">
                            <option value="licence">자격증</option>
                            <option value="language">어학</option>
                            <option value="grade">학점</option>
                            <option value="internship">인턴</option>
                            <option value="volunteer">봉사</option>
                            <option value="work">업무</option>
                        </optgroup>
                        <optgroup label="일반">
                            <option value="general">일반</option>
                        </optgroup>
                        <!--
                            <optgroup label="챌린지">
                                <option value="study">공부</option>
                                <option value="health">건강</option>
                                <option value="habbit">습관</option>
                                <option value="reading">독서</option>
                                <option value="hobby">취미</option>
                                <option value="work">업무</option>
                            </optgroup>
                        -->
                    </select>
                </div>
                <label class="grid_three">
                    <span>시작/종료:&nbsp;</span>
                </label>
                <div class="grid_four">
                    <input class="grid_four_box" type="date" name="start_date" value="2021-08-20">
                    <input class="grid_four_box" type="date" name="end_date" value="2021-08-27">
                </div>
                <label class="grid_five">
                    <span>제목:&nbsp;</span>
                </label>
                <div class="grid_six">
                    <input class="grid_six_box" name="title" type="text">
                </div>
                <label class="grid_seven">
                    <span>글:&nbsp;</span>
                </label>
                <div class="grid_eight">
                    <input class="grid_eight_box" name="detail" type="text" value="기록할 내용을 입력해보세요.">
                </div>
                <div class="grid_nine">                
                    <button class="grid_nine_box" type="submit">
                        
                            <span>등록하기</span>
                        
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
<script src="{% static 'js/portfolio.js' %}" ></script>
{% endblock content%}

templates/records/records_write_scrap.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/records/records_write.css' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}
{% block islogin %}
{% if request.user.is_authenticated %}
<a href="{% url 'users:logout' %}">Log out</a>
{% endif %} 
{% if request.user.is_authenticated is False %}
<a href="{% url 'users:login' %}">Log In</a>
{% endif %} 
{% endblock islogin %}
{% block content %}
<div class="left_right_all_page">
    <div></div>
    <div class="portfolio_main">
        <form class="index_three">
            <div class="index_three_window">
                <label class="grid_one">
                    <span>카테고리:&nbsp;</span>
                </label>
                <div class="grid_two">
                    <input class="grid_two_box" placeholder="SCRAP" />
                </div>
                <label class="grid_three">
                    <span></span>
                </label>
                <div class="grid_four">
                </div>
                <label class="grid_five">
                    <span>제목:&nbsp;</span>
                </label>
                <div class="grid_six">
                    <input class="grid_six_box" type="text">
                </div>
                <label class="grid_seven">
                    <span>글:&nbsp;</span>
                </label>
                <div class="grid_eight">
                    <input class="grid_eight_box" type="text">
                </div>
                <div class="grid_nine">                
                    <button class="grid_nine_box">
                        <a class="grid_nine_button" href="{% url 'records:main' %}">
                            <span>등록하기</span>
                        </a>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
<script src="{% static 'js/portfolio.js' %}" ></script>
{% endblock content%}