core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.intro_view, name="intro"),
    path("try/", views.try_view, name="try"),
]

app_name = "core"

hackathon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("records/", include("records.urls", namespace="records")),
    path("portfolios/", include("portfolios.urls", namespace="portfolios")),
    path("challenges/", include("challenges.urls", namespace="challenges")),
    path("connects/", include("connects.urls", namespace="connects")),
    path("repositories/", include("repositories.urls", namespace="repositories")),
    path("", include("core.urls", namespace="core")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("main/", views.MainView.as_view(), name="main"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.log_out, name="logout"),
]

app_name = "users"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="shortcut icon" href="{% static 'image/nada_logo_final.png' %}" >
    {% block css %}
    {% endblock css %}
    <title>{% block page_title %}{% endblock page_title %}</title>
</head>
<a href="#">
    <div class="top_button" style="position: fixed; bottom: 25px; right: 25px;">
        TOP
    </div></a>
<body>
    <header>
        {% block nav %}
            <div class="normal_nav">
                <div class="navigation_bar">
                    <div class="empty"></div>
                    <div class="nav_profile_box">
                        <div class="nav_profile">
                            <img class="imagea" src="{% static 'image/nav_profile.jpeg'%}"></img>
                            <div class="green_small_box">
                                <div class="green_small"></div>
                            </div>
                        </div>
                    </div>
                    <div class="empty"></div>
                    <a class="nav_category" href="{% url 'users:main' %}">
                        <div class="nav_boxbox" >
                            <img class="imageaz" src="{% static 'image/logo_four.png'%}"></img>
                        </div>
                        <span class="nav_boxtitle">메인</span>
                    </a>
                    <div class="empty"></div>
                    <a class="nav_category"  href="{% url 'portfolios:main' %}">
                        <div class="nav_boxbox">
                            <img class="imageaz" src="{% static 'image/logo_one.png'%}"></img>
                        </div>
                        <span class="nav_boxtitle">포트폴리오</span>
                        
                    </a>
                    <div class="empty"></div>
                    <a class="nav_category" href="{% url 'challenges:main' %}">
                        <div class="nav_boxbox" >
                            <img class="imageaz" src="{% static 'image/logo_eight.png'%}"></img>
                        </div>
                        <span class="nav_boxtitle">챌린지</span>
                    </a>
                    <div class="empty"></div>
                    <a class="nav_category" href="{% url 'records:main' %}">
                        <div class="nav_boxbox" >
                            <img class="imageaz" src="{% static 'image/logo_six.png'%}"></img>
                        </div>
                        <span class="nav_boxtitle">기록</span>
                    </a>
                    <div class="empty"></div>
                    <a class="nav_category" href="{% url 'repositories:main' %}">
                        <div class="nav_boxbox" >
                            <img class="imageaz" src="{% static 'image/logo_seven.png'%}"></img>
                        </div>
                        <span class="nav_boxtitle">보관함</span>
                    </a>
                    <div class="empty"></div>
                    <a class="nav_category" href="{% url 'connects:main' %}">
                        <div class="nav_boxbox" >
                            <img class="imageaz" src="{% static 'image/logo_two.png'%}"></img>
                        </div>
                        <span class="nav_boxtitle">커넥트</span>
                    </a>
                    
                    
                </div>
            </div>
            <div class="status-bar">
                <a href="{% url 'users:main' %}"><span class="main_logo">N A D A</span></a>
                <div class="status-bar_sub">
                    <div>
                        {% if request.user.is_authenticated %}
                        {% block profile %}
                        <div class="hello">
                            <span>{{user.username}}님, 안녕하세요</span>
                        </div>
                        {% endblock profile %}
                        {% endif %}
                    </div>
                    <button class="text_button">
                        <div class="z1001"> <i class="far fa-comment-dots fa-3x "></i></div>
                        <div class="green_small_boxs">
                            <div class="green_smalls">N</div>
                        </div>
                    </button>
                    <button class="login_button">
                        {% block islogin %}
                        
                        {% endblock islogin %}
                    </button>
                    
                </div>
            </div>
            <div class="message_big">
                <div class="message">
                    <div id="qchat-screen">
                        <div class="qalt-header">
                            <div class="qalt-header__column">
                                <i class="aaa fas fa-angle-left fa-2x"></i>
                            </div>
                            <div class="qalt-header__column">
                                <h1 class="qalt-header__title">이두희</h1>
                            </div>
                            <div class="qalt-header__column">
                                <span><i class="bbb fas fa-search fa-lg"></i></span>
                            </div>
                        </div>
                        <main class="qmain-screen qmain-chat">
                            <div class="qchat__timestamp">Tuesday, june 30, 2020</div>
                        </main>
                        <div class="qmessage-row">
                            <img class="images" src="{% static 'image/nav_profile.jpeg'%}"></img>
                            <div class="qmessage-row__content">
                                <span class="qmessage__author">이두희</span>
                                <div class="qmessage__info">
                                <span class="qmessage__bubble qfirst-chat">Hi!</span>
                                <span class="qmessage__time">21:27</span>
                                </div>
                            </div>
                        </div>
                        <div class="qmessage-row qmessage-row--own">
                            <div class="qmessage-row__content">
                            <div class="qmessage__info">
                                <span class="qqmessage__bubble qsecond-chat">Hi! nice to meet you!</span>
                                <span class="qmessage__time">21:27</span>
                            </div>
                            </div>
                        </div>
                        </main>
                    
                        <from class="qreply">
                            <div class="qreply__column">
                                <input type="qtext" placeholder="대화 내용을 입력하세요" />
                                <i class="airplane far fa-paper-plane fa-lg"></i>
                            </div>
                        </from>
                    </div>
                </div>
            </div>
        {% endblock nav %}
    </header>

    {% block content%}{% endblock %}

    <script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
    <script>
        var navbar = document.querySelector(".navigation_bar")
        var titles = document.querySelectorAll(".nav_boxtitle")
        navbar.addEventListener("mouseover",function(e){
            titles.forEach(function(title){
                title.style.display="block"
                title.style.animationName = "navtitle-start"
                title.style.animationPlayState="running"

            })
        })
        navbar.addEventListener("mouseleave",function(e){
            titles.forEach(function(title){
                title.style.animationName = "navtitle-end"
                title.style.animationPlayState="running"
                title.style.display="none"
            })
        })
        var comment = document.querySelector(".z1001")
        var message = document.querySelector(".message_big")
        var body = document.querySelector("body")
        comment.addEventListener("click",function(e){
            if (message.style.display==="none") {
                message.style.display = "block"
               
            } else {
                message.style.display = "none"
            }
            
        })
    </script>
</body>
</html>

templates/intro.html
{% extends "base.html" %}
{% load static %}
{% block nav %}{% endblock nav %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/users/intro.css' %}">
        <link rel="shortcut icon" href="{% static 'image/nada_logo_final.png' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}
{% block content %}

<div class="status-bar">
    <span class="main_logo">N A D A</span>
    <div></div>
    <div></div>
    {% if user.is_authenticated %}
    <button class="login_button"><a href="{% url 'users:logout' %}">Log out</a></button>
    {% endif %}
    {% if user.is_authenticated is False %}
    <button class="login_button"><a href="{% url 'users:login' %}">Log In</a></button>
    {% endif %}
</div>
<div class="video-title">
    <div></div>
    <div class="video-title-main">
        <div class="video-title-main-title">N A D A</div>
        <div>: 가장 NADA운 나의 기록</div>
    </div>
</div>
<div class="video-titles">
    <div class="page_down">
        <i class="page_down_button fas fa-arrow-circle-down fa-2x"></i>
    </div>
</div>
<div class="videobox">
    <video
    class="main_video"
    autoplay
    loop
    muted
    preload="auto">
    <source src="{% static 'image/main.mp4'%}" type="video/mp4"></source>
</video>
<div class="index_two">
        <div class="index_two_logo_box">
            <img class="imagez" src="{% static 'image/intro_two_logo.png'%}"></img>
        </div>
        <span class="index_two_sub_title">나의 과거, 현재, 미래를 담은 기록</span>
        <span class="index_two_sub_title">가장 나다운 나를 기록할 수 있는 사이트 NADA입니다.</span>
</div>
<div class="index_three">
    <div class="index_three_info">
        <div class="index_three_box">
            <div class="index_three_sub_one_title"></div>
            <div class="index_three_title">Portfolio</div>
            <div class="index_three_sub_two_title">당신이 걸어온 발자취를 NADA에 모아보세요.</div>
            <div class="index_three_sub_two_title">현재 꿈꾸는 직무가 있다면, 현직자들의 포트폴리오를 </div>
            <div class="index_three_sub_two_title">참고해 앞으로의 목표를 설정해보세요.</div>
            <div class="index_three_sub_two_title"></div>
        </div>
        <div class="intro_portfolio_button_box">
            <a href="{% url 'users:login' %}">
                <div class="intro_portfolio_button">
                    <span>Portfolio</span>
                    <div class="arrowhome">
                        <img class="imaget" src="{% static 'image/arrow.png'%}"></img>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="index_three_window">
        <div class="index_three_real_window">
            <img class="imaget" src="{% static 'image/intro_two_logo.png.jpg'%}"></img>
        </div>
    </div>
</div>
<div class="index_four">
    <div class="index_four_left">
        <div class="index_four_left_imagebox">
            <img class="imagetq" src="{% static 'image/intro_challenge_image.jpg'%}"></img>
        </div>
    </div>
    <div class="index_four_right">
        <div class="index_four_right_text">
            <div class="index_four_box">
                <div class="index_four_title">Challenge</div>
                <div class="index_four_sub_two_title">기간 내에 이루고 싶은 목표가 있나요?</div>
                <div class="index_four_sub_two_title">주저하지 말고, NADA에서 도전해보세요.</div>
                <div class="index_four_sub_two_title">주변 지인들에게 챌린지를 공유하며 동기부여를</div>
                <div class="index_four_sub_two_title">얻어도 좋아요.</div>
            </div>
        </div>
        <div class="intro_challenge_button_box">
            <a href="{% url 'users:login' %}">
                <div class="intro_challenge_button">
                    <span>Challenge</span>
                    <div class="arrowhome">
                        <img class="imaget" src="{% static 'image/arrow.png'%}"></img>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>
<div class="index_five">
    <div class="index_five_info">
        <div class="index_five_box">
            <div class="index_five_title">
                <span>Record</span>
            </div>
            <div class="index_five_sub_two_title">당신이 지나온 포트폴리오, 앞으로의 챌린지,</div>
            <div class="index_five_sub_two_title">현 상황을 담은 스크랩까지 NADA에 모두 기록해 모아보세요.</div>
        </div>
        <a href="{% url 'users:login' %}">
            <div class="intro_record_button">
                <span>Record</span>
                <div class="arrowhome">
                    <img class="imaget" src="{% static 'image/arrow.png'%}"></img>
                </div>
            </div>
        </a>
    </div>
    <div class="index_five_window">
        <div class="index_five_real_window">
            <img class="imagetqqq" src="{% static 'image/computers.png'%}"></img>
            <div class="inner_video">
                <video
    class="main_videozzz"
    autoplay
    loop
    muted
    preload="auto">
    <source src="{% static 'image/record_video.mp4'%}" type="video/mp4"></source>
</video>
            </div>
        </div>
    </div>
</div>
<div class="index_six">
    <div class="index_six_left">
        <div class="index_six_left_circle">
            <img class="imaget" src="{% static 'image/six_left.png'%}"></img>
        </div>
    </div>
    <div class="index_six_fight">
        <div class="index_six_fight_text">흩어진 자료들을 한 곳에 보관해 보세요!</div>
        <div class="index_six_fight_text">포트폴리오를 제작하거나, 이력서를 작성할 때 등</div>
        <div class="index_six_fight_text">당신이 필요한 순간,</div>
        <div class="index_six_fight_text">그 언제라도 NADA에서 정보를 꺼내쓰세요.</div>
        <a href="{% url 'users:login' %}">
            <div class="intro_repo_button">
                <span>Repository</span>
                <div class="arrowhome">
                    <img class="imaget" src="{% static 'image/arrow.png'%}"></img>
                </div>
            </div>
        </a>
    </div>
</div>
<div class="index_seven">
    <div class="index_seven_title">
        <span class="index_seven_real_title">Connect</span>
        <a href="{% url 'users:login' %}">
            <div class="intro_connect_button">
                <span>Connect</span>
                <div class="arrowhome">
                    <img class="imaget" src="{% static 'image/arrow.png'%}"></img>
                </div>
            </div>
        </a>
    </div>
    <div class="videoboxz">
        <video
        class="main_videoz"
        autoplay
        loop
        muted
        preload="auto">
        <source src="{% static 'image/connect_real_video.mp4'%}" type="video/mp4"></source>
        </video>
    </div>
    <div class="index_seven_text">
        <span class="index_seven_textdowna">현직자의 포트폴리오가 궁금하지는 않았나요? </span>
        <span class="index_seven_textdownb">혹은 어떤 것을 챌린지 해야 할지 막막하지는 않았나요?</span>
        <span class="index_seven_textdownc"> 지금 커넥트에서는 이 모든 정보와 함께 공모전, 스터디원 모집까지도 확인해 볼 수 있어요.</span>
    </div>
</div>
<div class="index_eight">
    <span class="index_eight_one">당신을 소개하는 순간</span>
    <span class="index_eight_two">자신있게 건넬 수 있는 단 하나의 사이트</span>
    <div class="index_eight_logo_box_box">
        <span class="eight_text">바로,</span>
        <div class="index_eight_logo_box">
            <img class="imagez" src="{% static 'image/intro_two_logo.png'%}"></img>
        </div>
    </div>
</div>
<div class="footer">
    <div class="footer_logo_box">
        <span class="footer_logo">N A D A</span>
        <div class="footer_tag">
            <a href="http://www.facebook.com/">
                <i class="fab fa-facebook-square fa-xs"></i>
            </a>
            <a href="http://www.instagram.com/">
                <i class="fab fa-instagram fa-xs"></i>
            </a>
            <a href="http://www.twitter.com/">
                <i class="fab fa-twitter fa-xs"></i>
            </a>
            <a href="http://google.com/">
                <i class="fab fa-google-play fa-xs"></i>
            </a>
        </div>
    </div>
    <div class="footer_text">
        <span>인하대학교 멋쟁이사자처럼 중앙 해커톤</span>
        <span>Developer : 임예지, 손민혁, 이규원, 이승찬</span>
        <span>13 .08 2021</span>
    </div>
</div>
<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
{% endblock content %}

templates/main.html
{% extends "base.html" %}
{% load static %}
<head>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/users/main.css' %}">
    {% endblock css %}
</head>
{% block page_title %} 나다 : NADA {% endblock %}
{% block nav %}{% endblock nav %}
{% block content %}
<div class="status-bar">
  <a href="{% url 'core:intro' %}"><span class="main_logo">N A D A</span></a>
  <div></div>
  <div></div>
  {% if user.is_authenticated %}
    <button class="login_button"><a href="{% url 'users:logout' %}">Log out</a></button>
  {% endif %}
  {% if user.is_authenticated is False %}
    <button class="login_button"><a href="{% url 'users:login' %}">Log In</a></button>
  {% endif %}
</div>
<div class="main_back"></div>
<div class="circle">
  <div></div>
  <div class="circle_box_one">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
    <a class="line" href="{% url 'portfolios:main' %}">
      <div class="mother_one">
        <span class="oneone">포트폴리오</span>
        <div class=" circle_one">
          <div class="box box_one">
            <span class="box_one_text">인생 곡선을 담은 나만의 포트폴리오</span>
          </div>
        </div>
      </div>
    </a>
    <a class="line" href="{% url 'challenges:main' %}">
      <div class="mother_two">
        <span class="twotwo">CHALLENGE</span>
        <div class=" circle_two">
          <div class="box box_two">
            <span class="box_one_text">
              <span>새로운 목표 설정과 일일 기록</span>
            </span>
          </div>
        </div>
      </div>
    </a>
    <div></div>
    <div></div>
    <div></div>
    <div></div>
  </div>
  <div class="circle_box_two">
    <div></div>
    <div></div>
    <a class="line" href="{% url 'repositories:main' %}">
      <div class="mother_three">
        <span class="threethree">보관함</span>
        <div class=" circle_three">
          <div class="box box_three">
            <span class="box_one_texta">
              <span>참조하고 싶은 다른 유저의 NADA</span>
              <span>기록 보관함</span>
            </span>
          </div>
        </div>
      </div>
    </a>
    <a class="line" href="{% url 'records:main' %}">
      <div class="mother_four">
        <span class="fourfour">기록</span>
        <div class=" circle_four">
          <div class="box box_four">
            <span class="box_one_texta">
              <span>활동, 도전, 스크랩 모든 것을 담은</span>
              <span>나의 과거</span>
            </span>
          </div>
        </div>
      </div>
    </a>
    <a class="line" href="{% url 'connects:main' %}">
      <div class="mother_five">
        <span class="fivefive">CONNECT</span>
        <div class=" circle_five">
          <div class="box box_five">
            <span class="box_one_texta">
              <span>같은 꿈을 공유하는 사람들을</span>
              <span>만나는 공간</span>
          </div>
        </div>
      </div>
    </a>
    <div></div>
    <div></div>
  </div>
</div>
<script
    src="https://kit.fontawesome.com/4d118135bb.js"
    crossorigin="anonymous"
    ></script>
{% endblock content %}

templates/try.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/try.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="emo-box" >
        <div ><i class="fas fa-plus plus icon fa-2x"></i></div>
        <ul class="menu">
            <li>
                <div class="emoji emoji--like">
                    <div class="emoji__hand">
                        <div class="emoji__thumb">
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <div class="emoji emoji--love">
                    <div class="emoji__heart">
                    </div>
                </div>
            </li>
            <li>
                <div class="emoji emoji--wow">
                    <div class="emoji__face">
                        <div
                            class="emoji__eyebrows">
                        </div>
                        <div class="emoji__eyes">
                        </div>
                        <div class="emoji__mouth">
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    
    
    <form action="{% url 'core:try' %}" method="POST">
        {% csrf_token %}
        <label for="username">USERNAME</label>
        <input id="username"  name="username" value={{variable}}><br>
        <label for="num1">20</label>
        <input id="num1" type="number" name="number1"><br>
        <label for="text1">설명</label>
        <input id="text1" type="text" name="text1"><br>
        <label for="num2">21</label>
        <input id="num2" type="number" name="number2"><br>
        <label for="text2">설명</label>
        <input id="text2" type="text" name="text2"><br>
        <label for="num3">22</label>
        <input id="num3" type="number" name="number3"><br>
        <label for="text3">설명</label>
        <input id="text3" type="text" name="text3"><br>
        <label for="num4">23</label>
        <input id="num4" type="number" name="number4"><br>
        <label for="text4">설명</label>
        <input id="text4" type="text" name="text4"><br>
        <label for="num5">24</label>
        <input id="num5" type="number" name="number5"><br>
        <label for="text5">설명</label>
        <input id="text5" type="text" name="text5"><br>
        <label for="num6">25</label>
        <input id="num6" type="number" name="number6"><br>
        <label for="text6">설명</label>
        <input id="text6" type="text" name="text6"><br>
        <label for="num7">26</label>
        <input id="num7" type="number" name="number7"><br>
        <label for="text7">설명</label>
        <input id="text7" type="text" name="text7"><br>
        <label for="num8">27</label>
        <input id="num8" type="number" name="number8"><br>
        <label for="text8">설명</label>
        <input id="text8" type="text" name="text8"><br>
        <label for="num9">28</label>
        <input id="num9" type="number" name="number9"><br>
        <label for="text9">설명</label>
        <input id="text9" type="text" name="text9"><br>
        <label for="num10">29</label>
        <input id="num10" type="number" name="number10"><br>
        <label for="text10">설명</label>
        <input id="text10" type="text" name="text10"><br>
        <button type="submit" >Submit</button>
    </form>
   
    
    <canvas id="line-chart" ></canvas>
    <canvas id="radar-chart" width="800" height="600"></canvas>

    <script src="https://kit.fontawesome.com/4d118135bb.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/try.js' %}" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
    <script>
        var text = {{text|safe}}.text
        var labels =   [[20],[21],[22],[23],[24],[25],[26],[27],[28],[29]]
        for (var i = 0; i < text.length; i++) { 
            labels[i].push(text[i])
    }
        var chart = new Chart(document.getElementById("line-chart"), {
        type: 'line',
        data: {
            labels:labels,
            datasets: [
                /*{ 
                data: [5,1,6,6,7,1,3,9,8,8],
                label: "이두희",
                borderColor: "#3e95cd",
                fill: false
            }, */
            { 
                data: [{{user|safe}}.user[0].num1,{{user|safe}}.user[0].num2,{{user|safe}}.user[0].num3,{{user|safe}}.user[0].num4,{{user|safe}}.user[0].num5,{{user|safe}}.user[0].num6,{{user|safe}}.user[0].num7,{{user|safe}}.user[0].num8,{{user|safe}}.user[0].num9,{{user|safe}}.user[0].num10],
                label: {{user|safe}}.user[0].username,
                borderColor: "#8e5ea2",
                fill: false
            }
        ]
        },
        options: {
            title: {
            display: true,
            text: 'Check your lifecycle graph with DooHee',
            fontSize: 50,
            
            
            }
        }
    
        })
        canvas = document.querySelector("canvas")
        canvas.style.cssText="display:block; width:70vw; height:70vh;"
        console.log(chart)
        ;
    </script>
</body>
</html>